//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsyeriMintika
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="IsyeriMintika.zhvl_pm_isyeri_mintika")]
    public interface zhvl_pm_isyeri_mintika
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:zhvl_pm_isyeri_mintika:ZHVL_PM_ISYERI_MINT" +
            "IKARequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<IsyeriMintika.ZHVL_PM_ISYERI_MINTIKAResponse1> ZHVL_PM_ISYERI_MINTIKAAsync(IsyeriMintika.ZHVL_PM_ISYERI_MINTIKARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZHVL_PM_ISYERI_MINTIKA
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZHVL_PM_S_ISYERI_MINTIKA
    {
        
        private string aRBPLField;
        
        private string kTEXTField;
        
        private string wERKSField;
        
        private string tPLNRField;
        
        private string kOSTLField;
        
        private string lTEXTField;
        
        private string oBJIDField;
        
        private string sTEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ARBPL
        {
            get
            {
                return this.aRBPLField;
            }
            set
            {
                this.aRBPLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string KTEXT
        {
            get
            {
                return this.kTEXTField;
            }
            set
            {
                this.kTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string WERKS
        {
            get
            {
                return this.wERKSField;
            }
            set
            {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TPLNR
        {
            get
            {
                return this.tPLNRField;
            }
            set
            {
                this.tPLNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string KOSTL
        {
            get
            {
                return this.kOSTLField;
            }
            set
            {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LTEXT
        {
            get
            {
                return this.lTEXTField;
            }
            set
            {
                this.lTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string OBJID
        {
            get
            {
                return this.oBJIDField;
            }
            set
            {
                this.oBJIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string STEXT
        {
            get
            {
                return this.sTEXTField;
            }
            set
            {
                this.sTEXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZHVL_PM_ISYERI_MINTIKAResponse
    {
        
        private ZHVL_PM_S_ISYERI_MINTIKA[] eT_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZHVL_PM_S_ISYERI_MINTIKA[] ET_DATA
        {
            get
            {
                return this.eT_DATAField;
            }
            set
            {
                this.eT_DATAField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZHVL_PM_ISYERI_MINTIKARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public IsyeriMintika.ZHVL_PM_ISYERI_MINTIKA ZHVL_PM_ISYERI_MINTIKA;
        
        public ZHVL_PM_ISYERI_MINTIKARequest()
        {
        }
        
        public ZHVL_PM_ISYERI_MINTIKARequest(IsyeriMintika.ZHVL_PM_ISYERI_MINTIKA ZHVL_PM_ISYERI_MINTIKA)
        {
            this.ZHVL_PM_ISYERI_MINTIKA = ZHVL_PM_ISYERI_MINTIKA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZHVL_PM_ISYERI_MINTIKAResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public IsyeriMintika.ZHVL_PM_ISYERI_MINTIKAResponse ZHVL_PM_ISYERI_MINTIKAResponse;
        
        public ZHVL_PM_ISYERI_MINTIKAResponse1()
        {
        }
        
        public ZHVL_PM_ISYERI_MINTIKAResponse1(IsyeriMintika.ZHVL_PM_ISYERI_MINTIKAResponse ZHVL_PM_ISYERI_MINTIKAResponse)
        {
            this.ZHVL_PM_ISYERI_MINTIKAResponse = ZHVL_PM_ISYERI_MINTIKAResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface zhvl_pm_isyeri_mintikaChannel : IsyeriMintika.zhvl_pm_isyeri_mintika, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class zhvl_pm_isyeri_mintikaClient : System.ServiceModel.ClientBase<IsyeriMintika.zhvl_pm_isyeri_mintika>, IsyeriMintika.zhvl_pm_isyeri_mintika
    {
        
        public zhvl_pm_isyeri_mintikaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IsyeriMintika.ZHVL_PM_ISYERI_MINTIKAResponse1> IsyeriMintika.zhvl_pm_isyeri_mintika.ZHVL_PM_ISYERI_MINTIKAAsync(IsyeriMintika.ZHVL_PM_ISYERI_MINTIKARequest request)
        {
            return base.Channel.ZHVL_PM_ISYERI_MINTIKAAsync(request);
        }
        
        public System.Threading.Tasks.Task<IsyeriMintika.ZHVL_PM_ISYERI_MINTIKAResponse1> ZHVL_PM_ISYERI_MINTIKAAsync(IsyeriMintika.ZHVL_PM_ISYERI_MINTIKA ZHVL_PM_ISYERI_MINTIKA)
        {
            IsyeriMintika.ZHVL_PM_ISYERI_MINTIKARequest inValue = new IsyeriMintika.ZHVL_PM_ISYERI_MINTIKARequest();
            inValue.ZHVL_PM_ISYERI_MINTIKA = ZHVL_PM_ISYERI_MINTIKA;
            return ((IsyeriMintika.zhvl_pm_isyeri_mintika)(this)).ZHVL_PM_ISYERI_MINTIKAAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
